### ISSUE TITLE
Should "full cast" be an allowed narrator tag?

### ISSUE THREAD

**Issue by djdembeck** [seanap/Audiobooks.bundle#16]
Personally, I think it should, because sometimes I want to see which books had a full cast narrating. Currently, the code from Unending prohibits this.
https://github.com/seanap/Audiobooks.bundle/blob/a5150edd958c999e99441f5968e1c3ef237c1b0e/Contents/Code/__init__.py#L728

**Comment by seanap** [comment]
Yes, that way if I want to listen to a full cast book but still want to browse the different genre's I can filter plex by full cast.

**Comment by djdembeck** [comment]
My thoughts exactly. I'll switch the behaviour over later today.

**Comment by djdembeck** [comment]
Added in https://github.com/seanap/Audiobooks.bundle/pull/23
