### ISSUE TITLE
Should narrator go to collections?

### ISSUE THREAD

**Issue by romanoh** [seanap/Audiobooks.bundle#22]
Right now the narrator(composer in the audio file tag) goes for style.
![imagem](https://user-images.githubusercontent.com/5342223/131393026-1ea67f27-3d4e-4ab2-a7af-c1505ac23f44.png)

i propose it goes for Collections.

**Comment by djdembeck** [comment]
Plex does not support music agents creating collections, so this is not possible.

**Comment by seanap** [comment]
You can manually make a smart collection of a specific narrator, but we can't automatically set collections with an agent

**Comment by romanoh** [comment]
Sorry to bother you, i saw in the plex docs, from the class Album, an attribute:
![imagem](https://user-images.githubusercontent.com/5342223/133859161-639c828d-1b37-4474-8ede-bec40fedaae9.png)
also i am working on one agent that as:
![imagem](https://user-images.githubusercontent.com/5342223/133859285-4dd02154-e023-4375-b927-c7f810fba98f.png)
But i am not there yet.
I am not a Python expert, far from it, i will like just your opinion if possible.
