### ISSUE TITLE
Year cannot be seen in search results if title/author are too long

### ISSUE THREAD

**Issue by rabelux** [seanap/Audiobooks.bundle#29]
Possible solutions (so far):
- truncate title and/or author if length exceed certain limit
- show year first as done here:
![grafik](https://user-images.githubusercontent.com/16120882/133273827-6cb3708a-a616-47d2-bdf0-fcc9d4bdb541.png)
- create separate column for year (if possible)

Discussion about this topic first started here:
https://github.com/seanap/Audiobooks.bundle/pull/28#discussion_r708302497

**Comment by djdembeck** [comment]
closed by https://github.com/seanap/Audiobooks.bundle/pull/28
