### ISSUE TITLE
Invalid type specifier

### ISSUE THREAD

**Issue by Arsur** [seanap/Audiobooks.bundle#30]
I always get `Exception loading item 'BOOKNAME' from bundle: invalid type specifier` when i try to add a book or refresh metadata. No Covers or descriptions are added.
Plex Server Version (1.24.3.5033, newest)

**Comment by djdembeck** [comment]
This is a known issue in the server. You'll need to go back to 1.24.2.

**Comment by davidszp** [comment]
I have encountered the same issue and going back to the 1.24.2 branch fixed it for me. 

Does the bundle need to be changed in order to accommodate the new Plex versions or is there an inherent bug with regard to metadata bundles in Plex server branches > 1.24.2?
