### ISSUE TITLE
New PMS causes issues with audiobook artwork and descriptions

### ISSUE THREAD

**Issue by kacymartin** [seanap/Audiobooks.bundle#35]
After updating to PMS Version 1.24.3.5033 it seems that new audiobooks are not being populated correctly after properly being matched. 

It appears that newly added books are showing with a title in the following format:
"Columbus Day" by Craig Alanson [2016]
Without a description and artwork. 

Reddit thread on this issue also appears here:
https://www.reddit.com/r/PleX/comments/pt6wzx/audiobooks_metadata_agent_is_no_longer_pulling/

**Comment by rabelux** [comment]
Have a look at #30.
@djdembeck maybe pin that issue so it's easier to find

**Comment by djdembeck** [comment]
Added as pinned known issue: https://github.com/seanap/Audiobooks.bundle/issues/36
