### ISSUE TITLE
Fuzzier searching for title

### ISSUE THREAD

**Issue by jt196** [seanap/Audiobooks.bundle#38]
Don't know whether this is related to how Plex works, I suspect it is the agent however. I'm running the most recent update of this agent (September 2021). 

Just going through my unmatched audiobooks and finding a couple of things: 

1. If there is a number in the book title e.g. "01 Eye of the World" - the matches will return empty. 

Is there a way to remove or relax this feature and create a fuzzier search system? Remove any potential series numbering etc? 

EDIT: removed reference to year (think it already does this)

**Comment by seanap** [comment]
The agents still need good tags in ALBUM and ALBUMARTIST.  It's probably best to remove the leading non-title characters from the ALBUM tag when tagging with mp3tag.  I have noticed this issue with some releases, but it's always solved by running the book through mp3tag before hand.  Making the agent match less accurate could lead to incorrect matching on other books.

Are you using the new Audnexus agent? The audiobook.bundle agent should be considered legacy, and no more development work will being going into it.

**Comment by jt196** [comment]
Yeah running the new Audnexus - it's working great. Just thought I'd share some feedback with a recent library clean up.

I did find another thing, @seanap, don't know if this is worth sharing/starting a new issue for. I found that the auto search sometimes returns different results to the manual search. This is in the 'match' or 'fix match' section. Don't know whether this might be something to do with the cached results? I though that a cache existed for every plugin, but could be wrong about that. Is it worth me deleting the `/config/Library/Application Support/Plex Media Server/Plug-in Support/Caches/com.plexapp.agents.audiobooks` folder to make things run a bit more smoothly?

**Comment by seanap** [comment]
I've noticed that with other agents as well, but I've never deleted the cache before.  No harm in deleting it, let me know if it helps.  I think the difference comes from what Plex uses to search.  The automatch could use bothe Title and Artist, but the manual search is only the Title.  Could also be a differnce between what type of search against the audible api, the manual matches allow searching of keywords (so ASIN searching works) where as the automatch searches the title and author specifically.

**Comment by djdembeck** [comment]
Seanap is correct: manual search only uses title.

**Comment by jt196** [comment]
Thanks for the clarification @seanap and @djdembeck, not much more to do here then. Great work on the plugin though, nice to see it's alive and kicking!
