### ISSUE TITLE
Audible is dying. Do you plan to support AudiobookGuild? 

### ISSUE THREAD

**Issue by Emasoft** [seanap/Audiobooks.bundle#41]
The main issue with this bundle is that there is only support for Audible, and lately that publisher had been abandoned by many important authors. The new rising publisher is AudiobookGuild, and most of the new audiobooks are exclusively on their platform. Not even on Amazon.
For example the popular series "Summoner" by Eric Vall is only available till volume 16 on Audible. If you want volume 17 to 22, you can only find them on AudiobookGuild. 
If I search for metadata for Summoner 22, I cannot find any result because the scraper only supports Audible. But the metadata is there on AudiobookGuild (see: https://audiobookguild.com/collections/summoner-by-eric-vall/products/summoner-22 ). 
Can you add that site to the scraper? Thanks!

**Comment by djdembeck** [comment]
Audible is very much not dying. They have the monopoly on the market. Maybe not forever but for now. 

AudiobookDB is where my time is being spent. It will be a provider-agnostic database

**Comment by Emasoft** [comment]
@djdembeck wrote:
> AudiobookDB is where my time is being spent. It will be a provider-agnostic database

Can't find it on github. Even a google search doesn't return anything about AudiobookDB. So if we need the cover art and the metadata for Eric Vall "Summoner 22" audiobook, where should we go?

**Comment by seanap** [comment]
What I usually do in these situations is use my mp3tag audible script to tag the book to a book that audible has (ex. Summoner 16) then manually edit the tags/cover using goodreads or audiobookguild to update the metadata to the right book.  Then import it into plex but make sure to leave it unmatched. 

I do this for all books not on audible, it's not the best but it works well enough.

**Comment by Emasoft** [comment]
@seanap 
The audiobook I linked is just an example. I have many audiobooks missing from both Audible and Amazon, too many to edit each one manually. Almost all my favorite authors and series are exclusively published by AudiobookGuild now. They are the once Audible bestsellers authors, so in the future I, as many others, will most likely listen only to AudiobooksGuild productions. An Audible scraper is useless to me now. Please add some code to scrape the AudiobooksGuild website. 🙏😢
