### ISSUE TITLE
Plex Agent not pulling data if Author has initials

### ISSUE THREAD

**Issue by question69** [seanap/Audiobooks.bundle#43]
Recently discovered your agent and reworked my whole audiobook plex library, works great so far except one problem.

The Plex Agent seems to struggle to pull data, if the author has initials in his/her name. If I try to manually match their audiobooks it results in „no match“ at all.
All audiobooks ran through mp3tag with your settings before re-adding to plex.

Examples of „problematic“ authors 
- C Z Dunn
- C. L. Werner
- Ian St. Martin

**Comment by rabelux** [comment]
Your issue should be transferred here: https://github.com/djdembeck/Audnexus.bundle/issues

**Comment by question69** [comment]
> Your issue should be transferred here: https://github.com/djdembeck/Audnexus.bundle/issues

Oh im fairly new on github, is this an updated version of the agent?

**Comment by rabelux** [comment]
Yes.

**Comment by seanap** [comment]
To give some context before closing this out, for many years these tools didn't exsist.  When I originally wrote up the guide there was no audiobook agent and the original writeup was how to get some of the id3 tags into plex.  Then Macr0dev came out with his awesome agent, but I didn't like a few things such as series and genre were imported into plex so I created this repo that was a copy of his but modified slightly.  Then djdembeck came out with Audnexus which was so much better and made this repo obsolete.  The readme of this repo links to the Audnexus github page.

Audnexus normally handles the abbreviated names very well.  I have no problem matching those Authors in plex using Audnexus.

![image](https://user-images.githubusercontent.com/17012946/213244055-aab23a64-4a4a-48d2-88fc-f98cdbcdc8af.png)
![image](https://user-images.githubusercontent.com/17012946/213244162-b18ba3f8-0da4-4d3c-b114-83a39a1c8147.png)
![image](https://user-images.githubusercontent.com/17012946/213244371-c3d3f9a6-4874-4dd1-a4c5-4b64f6c14155.png)
